version: '2'

services:
  app:
    build:
      context: .
    image: spring-boot-hibernate-postgres-app
    container_name: app
    ports:
      - 8087:8080
    depends_on:
      - db
    stdin_open: true 
    tty: true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/film_app
      - SPRING_DATASOURCE_USERNAME=pgroot
      - SPRING_DATASOURCE_PASSWORD=pgroot
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    build:
      context: ./db
    image: spring-boot-hibernate-postgres-db
    container_name: postgres-db
    ports:
      - '5432'
    environment:
      - POSTGRES_USER=pgroot
      - POSTGRES_PASSWORD=pgroot