version: '2'

services:
  film-app:
    build:
      context: .
    container_name: app
    ports:
      - 8087:8080
    depends_on:
      - db
    stdin_open: true 
    tty: true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/film_app
      - SPRING_DATASOURCE_USERNAME=pgroot
      - SPRING_DATASOURCE_PASSWORD=pgroot
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  postgres-db:
    build:
      context: ./db
    container_name: db
    ports:
      - '5432'
    environment:
      - POSTGRES_USER=pgroot
      - POSTGRES_PASSWORD=pgroot