apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: film-app
  name: film-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: film-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: film-app
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: pgroot
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/film_app
            - name: SPRING_DATASOURCE_USERNAME
              value: pgroot
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          image: film-app
          imagePullPolicy: Never
          name: app
          ports:
            - containerPort: 8080
          resources: {}
          stdin: true
          tty: true
      restartPolicy: Always
status: {}
